# Generated by Django 4.2.6 on 2023-12-03 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='id',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
