# Generated by Django 4.2.6 on 2023-11-30 01:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='time',
            new_name='published',
        ),
        migrations.AddField(
            model_name='comment',
            name='contentType',
            field=models.TextField(default='UTC'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default='UTC'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(default='UTC', max_length=255),
            preserve_default=False,
        ),
    ]
