# Generated by Django 4.2.6 on 2023-12-08 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_alter_post_content'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendship',
            unique_together={('actor', 'object')},
        ),
    ]
