# Generated by Django 4.2.6 on 2023-12-01 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_rename_time_comment_published_comment_contenttype_and_more'),
        ('authors', '0003_alter_post_author'),
    ]

    operations = [
    ]
