# Generated by Django 4.2.6 on 2023-12-08 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0003_alter_friendship_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
