# Generated by Django 4.2.6 on 2023-12-09 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0004_delete_postimage'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendship',
            unique_together=set(),
        ),
    ]
