# Generated by Django 4.2.6 on 2023-10-29 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0004_remove_author_friends_friendship'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='profilePicture',
            field=models.ImageField(default='default-profile-picture.jpg', upload_to='media/profilepictures/'),
        ),
    ]
