# Generated by Django 4.2.6 on 2023-10-29 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0005_author_profilepicture'),
        ('authors', '0005_like'),
    ]

    operations = [
    ]
