# Generated by Django 4.2.6 on 2023-11-03 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0007_remove_post_content_post_content_type_post_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profilePicture',
            field=models.ImageField(default='default-profile-picture.jpg', upload_to='profilepictures/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='postimages/'),
        ),
    ]
