# Generated by Django 4.2.6 on 2023-11-08 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authors", "0009_alter_post_privacy"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="image",),
        migrations.RemoveField(model_name="post", name="image_url",),
        migrations.CreateModel(
            name="PostImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="postimages/")),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_images",
                        to="authors.post",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="images",
            field=models.ManyToManyField(
                related_name="posts_images", to="authors.postimage"
            ),
        ),
    ]
