# Generated by Django 4.2.6 on 2023-11-08 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authors", "0010_remove_post_image_remove_post_image_url_postimage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postimage",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="post_images",
                to="authors.post",
            ),
        ),
    ]
