# Generated by Django 4.2.6 on 2023-11-11 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0012_alter_postimage_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='images',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='postimages/'),
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
