# Generated by Django 4.2.6 on 2023-11-11 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0013_remove_post_images_post_image_delete_postimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
