# Generated by Django 4.2.6 on 2023-11-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0014_post_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nodes',
            fields=[
                ('url', models.URLField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
