# Generated by Django 4.2.6 on 2023-11-21 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0016_rename_nodes_node'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Node',
        ),
    ]
