# Generated by Django 4.2.6 on 2023-11-21 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0017_delete_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='is_a_node',
            field=models.BooleanField(default=False),
        ),
    ]
