# Generated by Django 4.2.6 on 2023-11-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0018_author_is_a_node'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.CharField(default='https://cmput404-project-backend-a299a47993fd.herokuapp.com/', max_length=255),
        ),
    ]
