name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.14 # Deploy backend
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "cmput404-project-backend"
          heroku_email: "jjavier@ualberta.ca"
      - uses: akhileshns/heroku-deploy@v3.12.14 # Deploy frontend
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "cmput404-project-frontend"
          heroku_email: "jjavier@ualberta.ca"